module.exports = {table:
{
  "*[,,object]" : {
     ",": ["[,,object]","*[,,object]"], 
     ";": [], 
     "]": [], 
     ".": []}, 
  "*[;,?[verb,objectList]]" : {
     ";": ["[;,?[verb,objectList]]","*[;,?[verb,objectList]]"], 
     "]": [], 
     ".": []}, 
  "*object" : {
     "IRI_REF": ["object","*object"], 
     "BLANK_NODE_LABEL": ["object","*object"], 
     "ANON": ["object","*object"], 
     "NIL": ["object","*object"], 
     "(": ["object","*object"], 
     "[": ["object","*object"], 
     "PNAME_LN": ["object","*object"], 
     "PNAME_NS": ["object","*object"], 
     "INTEGER": ["object","*object"], 
     "DECIMAL": ["object","*object"], 
     "DOUBLE": ["object","*object"], 
     "true": ["object","*object"], 
     "false": ["object","*object"], 
     "STRING_LITERAL_QUOTE": ["object","*object"], 
     "STRING_LITERAL_SINGLE_QUOTE": ["object","*object"], 
     "STRING_LITERAL_LONG_SINGLE_QUOTE": ["object","*object"], 
     "STRING_LITERAL_LONG_QUOTE": ["object","*object"], 
     ")": []}, 
  "*statement" : {
     "@prefix": ["statement","*statement"], 
     "@base": ["statement","*statement"], 
     "PREFIX": ["statement","*statement"], 
     "BASE": ["statement","*statement"], 
     "[": ["statement","*statement"], 
     "IRI_REF": ["statement","*statement"], 
     "BLANK_NODE_LABEL": ["statement","*statement"], 
     "ANON": ["statement","*statement"], 
     "NIL": ["statement","*statement"], 
     "(": ["statement","*statement"], 
     "PNAME_LN": ["statement","*statement"], 
     "PNAME_NS": ["statement","*statement"], 
     "$": []}, 
  "?[verb,objectList]" : {
     "a": ["[verb,objectList]"], 
     "IRI_REF": ["[verb,objectList]"], 
     "PNAME_LN": ["[verb,objectList]"], 
     "PNAME_NS": ["[verb,objectList]"], 
     ";": [], 
     "]": [], 
     ".": []}, 
  "?or([LANGTAG,[^^,iri]])" : {
     "LANGTAG": ["or([LANGTAG,[^^,iri]])"], 
     "^^": ["or([LANGTAG,[^^,iri]])"], 
     ";": [], 
     ",": [], 
     "IRI_REF": [], 
     "BLANK_NODE_LABEL": [], 
     "ANON": [], 
     "NIL": [], 
     "(": [], 
     "[": [], 
     "PNAME_LN": [], 
     "PNAME_NS": [], 
     "INTEGER": [], 
     "DECIMAL": [], 
     "DOUBLE": [], 
     "true": [], 
     "false": [], 
     "STRING_LITERAL_QUOTE": [], 
     "STRING_LITERAL_SINGLE_QUOTE": [], 
     "STRING_LITERAL_LONG_SINGLE_QUOTE": [], 
     "STRING_LITERAL_LONG_QUOTE": [], 
     "]": [], 
     ")": [], 
     ".": []}, 
  "?predicateObjectList" : {
     "a": ["predicateObjectList"], 
     "IRI_REF": ["predicateObjectList"], 
     "PNAME_LN": ["predicateObjectList"], 
     "PNAME_NS": ["predicateObjectList"], 
     ".": []}, 
  "[,,object]" : {
     ",": [",","object"]}, 
  "[;,?[verb,objectList]]" : {
     ";": [";","?[verb,objectList]"]}, 
  "[^^,iri]" : {
     "^^": ["^^","iri"]}, 
  "[blankNodePropertyList,?predicateObjectList]" : {
     "[": ["blankNodePropertyList","?predicateObjectList"]}, 
  "[storeProperty,a]" : {
     "a": ["storeProperty","a"]}, 
  "[storeProperty,predicate]" : {
     "IRI_REF": ["storeProperty","predicate"], 
     "PNAME_LN": ["storeProperty","predicate"], 
     "PNAME_NS": ["storeProperty","predicate"]}, 
  "[subject,predicateObjectList]" : {
     "IRI_REF": ["subject","predicateObjectList"], 
     "BLANK_NODE_LABEL": ["subject","predicateObjectList"], 
     "ANON": ["subject","predicateObjectList"], 
     "NIL": ["subject","predicateObjectList"], 
     "(": ["subject","predicateObjectList"], 
     "PNAME_LN": ["subject","predicateObjectList"], 
     "PNAME_NS": ["subject","predicateObjectList"]}, 
  "[triples,.]" : {
     "[": ["triples","."], 
     "IRI_REF": ["triples","."], 
     "BLANK_NODE_LABEL": ["triples","."], 
     "ANON": ["triples","."], 
     "NIL": ["triples","."], 
     "(": ["triples","."], 
     "PNAME_LN": ["triples","."], 
     "PNAME_NS": ["triples","."]}, 
  "[verb,objectList]" : {
     "a": ["verb","objectList"], 
     "IRI_REF": ["verb","objectList"], 
     "PNAME_LN": ["verb","objectList"], 
     "PNAME_NS": ["verb","objectList"]}, 
  "base" : {
     "@base": ["@base","IRI_REF","."]}, 
  "blankNode" : {
     "BLANK_NODE_LABEL": ["or([BLANK_NODE_LABEL,ANON])"], 
     "ANON": ["or([BLANK_NODE_LABEL,ANON])"]}, 
  "blankNodePropertyList" : {
     "[": ["[","predicateObjectList","]"]}, 
  "booleanLiteral" : {
     "true": ["or([true,false])"], 
     "false": ["or([true,false])"]}, 
  "collection" : {
     "NIL": ["NIL"], 
     "(": ["(","*object",")"]}, 
  "directive" : {
     "@prefix": ["or([prefixID,base,sparqlPrefix,sparqlBase])"], 
     "@base": ["or([prefixID,base,sparqlPrefix,sparqlBase])"], 
     "PREFIX": ["or([prefixID,base,sparqlPrefix,sparqlBase])"], 
     "BASE": ["or([prefixID,base,sparqlPrefix,sparqlBase])"]}, 
  "iri" : {
     "IRI_REF": ["or([IRI_REF,prefixedName])"], 
     "PNAME_LN": ["or([IRI_REF,prefixedName])"], 
     "PNAME_NS": ["or([IRI_REF,prefixedName])"]}, 
  "literal" : {
     "INTEGER": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "DECIMAL": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "DOUBLE": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "true": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "false": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "STRING_LITERAL_QUOTE": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "STRING_LITERAL_SINGLE_QUOTE": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "STRING_LITERAL_LONG_SINGLE_QUOTE": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "STRING_LITERAL_LONG_QUOTE": ["or([rdfLiteral,numericLiteral,booleanLiteral])"]}, 
  "numericLiteral" : {
     "INTEGER": ["or([INTEGER,DECIMAL,DOUBLE])"], 
     "DECIMAL": ["or([INTEGER,DECIMAL,DOUBLE])"], 
     "DOUBLE": ["or([INTEGER,DECIMAL,DOUBLE])"]}, 
  "object" : {
     "IRI_REF": ["or([iri,blankNode,collection,blankNodePropertyList,literal])"], 
     "BLANK_NODE_LABEL": ["or([iri,blankNode,collection,blankNodePropertyList,literal])"], 
     "ANON": ["or([iri,blankNode,collection,blankNodePropertyList,literal])"], 
     "NIL": ["or([iri,blankNode,collection,blankNodePropertyList,literal])"], 
     "(": ["or([iri,blankNode,collection,blankNodePropertyList,literal])"], 
     "[": ["or([iri,blankNode,collection,blankNodePropertyList,literal])"], 
     "PNAME_LN": ["or([iri,blankNode,collection,blankNodePropertyList,literal])"], 
     "PNAME_NS": ["or([iri,blankNode,collection,blankNodePropertyList,literal])"], 
     "INTEGER": ["or([iri,blankNode,collection,blankNodePropertyList,literal])"], 
     "DECIMAL": ["or([iri,blankNode,collection,blankNodePropertyList,literal])"], 
     "DOUBLE": ["or([iri,blankNode,collection,blankNodePropertyList,literal])"], 
     "true": ["or([iri,blankNode,collection,blankNodePropertyList,literal])"], 
     "false": ["or([iri,blankNode,collection,blankNodePropertyList,literal])"], 
     "STRING_LITERAL_QUOTE": ["or([iri,blankNode,collection,blankNodePropertyList,literal])"], 
     "STRING_LITERAL_SINGLE_QUOTE": ["or([iri,blankNode,collection,blankNodePropertyList,literal])"], 
     "STRING_LITERAL_LONG_SINGLE_QUOTE": ["or([iri,blankNode,collection,blankNodePropertyList,literal])"], 
     "STRING_LITERAL_LONG_QUOTE": ["or([iri,blankNode,collection,blankNodePropertyList,literal])"]}, 
  "objectList" : {
     "IRI_REF": ["object","*[,,object]"], 
     "BLANK_NODE_LABEL": ["object","*[,,object]"], 
     "ANON": ["object","*[,,object]"], 
     "NIL": ["object","*[,,object]"], 
     "(": ["object","*[,,object]"], 
     "[": ["object","*[,,object]"], 
     "PNAME_LN": ["object","*[,,object]"], 
     "PNAME_NS": ["object","*[,,object]"], 
     "INTEGER": ["object","*[,,object]"], 
     "DECIMAL": ["object","*[,,object]"], 
     "DOUBLE": ["object","*[,,object]"], 
     "true": ["object","*[,,object]"], 
     "false": ["object","*[,,object]"], 
     "STRING_LITERAL_QUOTE": ["object","*[,,object]"], 
     "STRING_LITERAL_SINGLE_QUOTE": ["object","*[,,object]"], 
     "STRING_LITERAL_LONG_SINGLE_QUOTE": ["object","*[,,object]"], 
     "STRING_LITERAL_LONG_QUOTE": ["object","*[,,object]"]}, 
  "or([BLANK_NODE_LABEL,ANON])" : {
     "BLANK_NODE_LABEL": ["BLANK_NODE_LABEL"], 
     "ANON": ["ANON"]}, 
  "or([INTEGER,DECIMAL,DOUBLE])" : {
     "INTEGER": ["INTEGER"], 
     "DECIMAL": ["DECIMAL"], 
     "DOUBLE": ["DOUBLE"]}, 
  "or([IRI_REF,prefixedName])" : {
     "IRI_REF": ["IRI_REF"], 
     "PNAME_LN": ["prefixedName"], 
     "PNAME_NS": ["prefixedName"]}, 
  "or([LANGTAG,[^^,iri]])" : {
     "LANGTAG": ["LANGTAG"], 
     "^^": ["[^^,iri]"]}, 
  "or([PNAME_LN,PNAME_NS])" : {
     "PNAME_LN": ["PNAME_LN"], 
     "PNAME_NS": ["PNAME_NS"]}, 
  "or([[storeProperty,predicate],[storeProperty,a]])" : {
     "IRI_REF": ["[storeProperty,predicate]"], 
     "PNAME_LN": ["[storeProperty,predicate]"], 
     "PNAME_NS": ["[storeProperty,predicate]"], 
     "a": ["[storeProperty,a]"]}, 
  "or([[subject,predicateObjectList],[blankNodePropertyList,?predicateObjectList]])" : {
     "IRI_REF": ["[subject,predicateObjectList]"], 
     "BLANK_NODE_LABEL": ["[subject,predicateObjectList]"], 
     "ANON": ["[subject,predicateObjectList]"], 
     "NIL": ["[subject,predicateObjectList]"], 
     "(": ["[subject,predicateObjectList]"], 
     "PNAME_LN": ["[subject,predicateObjectList]"], 
     "PNAME_NS": ["[subject,predicateObjectList]"], 
     "[": ["[blankNodePropertyList,?predicateObjectList]"]}, 
  "or([directive,[triples,.]])" : {
     "@prefix": ["directive"], 
     "@base": ["directive"], 
     "PREFIX": ["directive"], 
     "BASE": ["directive"], 
     "[": ["[triples,.]"], 
     "IRI_REF": ["[triples,.]"], 
     "BLANK_NODE_LABEL": ["[triples,.]"], 
     "ANON": ["[triples,.]"], 
     "NIL": ["[triples,.]"], 
     "(": ["[triples,.]"], 
     "PNAME_LN": ["[triples,.]"], 
     "PNAME_NS": ["[triples,.]"]}, 
  "or([iri,blankNode,collection,blankNodePropertyList,literal])" : {
     "IRI_REF": ["iri"], 
     "PNAME_LN": ["iri"], 
     "PNAME_NS": ["iri"], 
     "BLANK_NODE_LABEL": ["blankNode"], 
     "ANON": ["blankNode"], 
     "NIL": ["collection"], 
     "(": ["collection"], 
     "[": ["blankNodePropertyList"], 
     "INTEGER": ["literal"], 
     "DECIMAL": ["literal"], 
     "DOUBLE": ["literal"], 
     "true": ["literal"], 
     "false": ["literal"], 
     "STRING_LITERAL_QUOTE": ["literal"], 
     "STRING_LITERAL_SINGLE_QUOTE": ["literal"], 
     "STRING_LITERAL_LONG_SINGLE_QUOTE": ["literal"], 
     "STRING_LITERAL_LONG_QUOTE": ["literal"]}, 
  "or([iri,blankNode,collection])" : {
     "IRI_REF": ["iri"], 
     "PNAME_LN": ["iri"], 
     "PNAME_NS": ["iri"], 
     "BLANK_NODE_LABEL": ["blankNode"], 
     "ANON": ["blankNode"], 
     "NIL": ["collection"], 
     "(": ["collection"]}, 
  "or([prefixID,base,sparqlPrefix,sparqlBase])" : {
     "@prefix": ["prefixID"], 
     "@base": ["base"], 
     "PREFIX": ["sparqlPrefix"], 
     "BASE": ["sparqlBase"]}, 
  "or([rdfLiteral,numericLiteral,booleanLiteral])" : {
     "STRING_LITERAL_QUOTE": ["rdfLiteral"], 
     "STRING_LITERAL_SINGLE_QUOTE": ["rdfLiteral"], 
     "STRING_LITERAL_LONG_SINGLE_QUOTE": ["rdfLiteral"], 
     "STRING_LITERAL_LONG_QUOTE": ["rdfLiteral"], 
     "INTEGER": ["numericLiteral"], 
     "DECIMAL": ["numericLiteral"], 
     "DOUBLE": ["numericLiteral"], 
     "true": ["booleanLiteral"], 
     "false": ["booleanLiteral"]}, 
  "or([true,false])" : {
     "true": ["true"], 
     "false": ["false"]}, 
  "predicate" : {
     "IRI_REF": ["iri"], 
     "PNAME_LN": ["iri"], 
     "PNAME_NS": ["iri"]}, 
  "predicateObjectList" : {
     "a": ["verb","objectList","*[;,?[verb,objectList]]"], 
     "IRI_REF": ["verb","objectList","*[;,?[verb,objectList]]"], 
     "PNAME_LN": ["verb","objectList","*[;,?[verb,objectList]]"], 
     "PNAME_NS": ["verb","objectList","*[;,?[verb,objectList]]"]}, 
  "prefixID" : {
     "@prefix": ["@prefix","PNAME_NS","IRI_REF","."]}, 
  "prefixedName" : {
     "PNAME_LN": ["or([PNAME_LN,PNAME_NS])"], 
     "PNAME_NS": ["or([PNAME_LN,PNAME_NS])"]}, 
  "rdfLiteral" : {
     "STRING_LITERAL_QUOTE": ["string","?or([LANGTAG,[^^,iri]])"], 
     "STRING_LITERAL_SINGLE_QUOTE": ["string","?or([LANGTAG,[^^,iri]])"], 
     "STRING_LITERAL_LONG_SINGLE_QUOTE": ["string","?or([LANGTAG,[^^,iri]])"], 
     "STRING_LITERAL_LONG_QUOTE": ["string","?or([LANGTAG,[^^,iri]])"]}, 
  "sparqlBase" : {
     "BASE": ["BASE","IRI_REF"]}, 
  "sparqlPrefix" : {
     "PREFIX": ["PREFIX","PNAME_NS","IRI_REF"]}, 
  "statement" : {
     "@prefix": ["or([directive,[triples,.]])"], 
     "@base": ["or([directive,[triples,.]])"], 
     "PREFIX": ["or([directive,[triples,.]])"], 
     "BASE": ["or([directive,[triples,.]])"], 
     "[": ["or([directive,[triples,.]])"], 
     "IRI_REF": ["or([directive,[triples,.]])"], 
     "BLANK_NODE_LABEL": ["or([directive,[triples,.]])"], 
     "ANON": ["or([directive,[triples,.]])"], 
     "NIL": ["or([directive,[triples,.]])"], 
     "(": ["or([directive,[triples,.]])"], 
     "PNAME_LN": ["or([directive,[triples,.]])"], 
     "PNAME_NS": ["or([directive,[triples,.]])"]}, 
  "storeProperty" : {
     "IRI_REF": [], 
     "PNAME_LN": [], 
     "PNAME_NS": [], 
     "a": []}, 
  "string" : {
     "STRING_LITERAL_QUOTE": ["STRING_LITERAL_QUOTE"], 
     "STRING_LITERAL_SINGLE_QUOTE": ["STRING_LITERAL_SINGLE_QUOTE"], 
     "STRING_LITERAL_LONG_SINGLE_QUOTE": ["STRING_LITERAL_LONG_SINGLE_QUOTE"], 
     "STRING_LITERAL_LONG_QUOTE": ["STRING_LITERAL_LONG_QUOTE"]}, 
  "subject" : {
     "IRI_REF": ["or([iri,blankNode,collection])"], 
     "BLANK_NODE_LABEL": ["or([iri,blankNode,collection])"], 
     "ANON": ["or([iri,blankNode,collection])"], 
     "NIL": ["or([iri,blankNode,collection])"], 
     "(": ["or([iri,blankNode,collection])"], 
     "PNAME_LN": ["or([iri,blankNode,collection])"], 
     "PNAME_NS": ["or([iri,blankNode,collection])"]}, 
  "triples" : {
     "[": ["or([[subject,predicateObjectList],[blankNodePropertyList,?predicateObjectList]])"], 
     "IRI_REF": ["or([[subject,predicateObjectList],[blankNodePropertyList,?predicateObjectList]])"], 
     "BLANK_NODE_LABEL": ["or([[subject,predicateObjectList],[blankNodePropertyList,?predicateObjectList]])"], 
     "ANON": ["or([[subject,predicateObjectList],[blankNodePropertyList,?predicateObjectList]])"], 
     "NIL": ["or([[subject,predicateObjectList],[blankNodePropertyList,?predicateObjectList]])"], 
     "(": ["or([[subject,predicateObjectList],[blankNodePropertyList,?predicateObjectList]])"], 
     "PNAME_LN": ["or([[subject,predicateObjectList],[blankNodePropertyList,?predicateObjectList]])"], 
     "PNAME_NS": ["or([[subject,predicateObjectList],[blankNodePropertyList,?predicateObjectList]])"]}, 
  "turtleDoc" : {
     "$": ["*statement","$"], 
     "@prefix": ["*statement","$"], 
     "@base": ["*statement","$"], 
     "PREFIX": ["*statement","$"], 
     "BASE": ["*statement","$"], 
     "[": ["*statement","$"], 
     "IRI_REF": ["*statement","$"], 
     "BLANK_NODE_LABEL": ["*statement","$"], 
     "ANON": ["*statement","$"], 
     "NIL": ["*statement","$"], 
     "(": ["*statement","$"], 
     "PNAME_LN": ["*statement","$"], 
     "PNAME_NS": ["*statement","$"]}, 
  "verb" : {
     "a": ["or([[storeProperty,predicate],[storeProperty,a]])"], 
     "IRI_REF": ["or([[storeProperty,predicate],[storeProperty,a]])"], 
     "PNAME_LN": ["or([[storeProperty,predicate],[storeProperty,a]])"], 
     "PNAME_NS": ["or([[storeProperty,predicate],[storeProperty,a]])"]}
},

keywords:/^(BASE|PREFIX)/i ,

punct:/^(a|\.|,|\(|\)|;|\[|\]|\^\^)/ ,

startSymbol:"turtleDoc",
acceptEmpty:true,
}